# Generated by Django 5.0.2 on 2024-08-08 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='title',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='image',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='snippet',
        ),
        migrations.AddField(
            model_name='posts',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
